apiVersion: v1
kind: Pod
metadata:
  name: demo-app
spec:
  containers:
  - name: demo-container
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: demo
          topologyKey: kubernetes.io/hostname
