apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-service
  labels:
    app: frontend-nginxapp
    tier: frontend
spec:
  type: LoadBalancer  # External LoadBalancer service
  selector:
    app: frontend-nginxapp
  ports:
    - name: http
      port: 80         # Service Port
      targetPort: 80   # Container Port
