apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport-service
  labels:
    app: backend-restapp
    tier: backend
spec:
  type: NodePort  # Exposes service on a static port on each node's IP
  selector:
    app: backend-restapp
  ports:
    - name: http
      port: 8080       # Service Port
      targetPort: 8080  # Container Port
      nodePort: 30080   # Static port on each node
